/**
 * QElectroTech project (.qet) import / export.
 *
 * Semantics followed (QET C++ sources, qelectrotech-source-mirror):
 *  - Scene origin: the folio border starts at Diagram::margin = 5 (BorderTitleBlock::
 *    updateRectangles / outsideBorderRect). Volt pages start at 0,0, so every scene coordinate is
 *    shifted by QET_MARGIN on import (qet - 5) and back on export (volt + 5).
 *  - Element instance x,y: scene position of the definition hotspot; orientation 0..3 = rotation
 *    of 90° steps, clockwise on screen (Element::fromXml: setRotation(90*ori)). No mirroring.
 *  - Instance <terminals><terminal x y orientation id>: x,y is the *inner* end of the terminal
 *    stub (Terminal::toXml writes dock_elmt_ = m_pos ± 4) in element-local coordinates and the
 *    definition orientation; the numeric `id` is unique per diagram and is what pre-0.7
 *    conductors reference (Element::fromXml matches entries to terminals by x/y/orientation).
 *  - Conductors reference terminals either by element1/terminal1 uuids (when the definition
 *    terminal has a uuid, Conductor::toXml) or by the numeric ids (findTerminal() in diagram.cpp).
 *  - Conductor geometry: <segment orientation length> are signed deltas chained from the scene
 *    dock point of terminal1 (Conductor::pathFromXml); the x/y attributes are only the item
 *    position and do not affect the absolute geometry. Without segments, or when the segments do
 *    not sum up to terminal2 within 1 unit, QET routes automatically
 *    (Conductor::generateConductorPath, ported below).
 *  - dynamic_elmt_text / diagram <input>: x,y = top-left of the text item box (4 px Qt document
 *    margin inside), relative to the element hotspot (resp. scene).
 */
import type {
  CompatItem,
  CompatLevel,
  CompatReport,
  Doc,
  ElemInst,
  ElementDef,
  FreeText,
  Junction,
  Orient,
  Page,
  PinDef,
  PlacedText,
  Pt,
  Shape,
  TextRole,
  TextStyle,
  TitleBlockTemplate,
  Wire,
  WireEnd,
} from "../model";
import { DEFAULT_TB, newDoc, newPage } from "../doc";
import { rotOrient, toScene } from "../geometry";
import { uid } from "../ids";
import { stableStringify } from "../stable-json";
import {
  defSignature,
  definitionElement,
  dockElmtOffset,
  halignFromQet,
  halignToQet,
  legacyInputToTopLeft,
  ORIENT_FROM_INDEX,
  ORIENT_INDEX,
  parseElmtNode,
  primsBBox,
  QET_VERSION,
} from "./elmt";
import { parseTitleBlockNode, serializeTitleBlockTemplate, titleBlockModified } from "./titleblock";
import {
  allAttrs,
  attr,
  bracedUuid,
  child,
  children,
  collapseIfEmpty,
  createEl,
  ensureChild,
  fmt,
  formatSubtree,
  htmlToPlain,
  insertIndented,
  int,
  isElement,
  isUuid,
  normUuid,
  num,
  optAttr,
  optNum,
  parseElement,
  parseQtFont,
  parseXml,
  plainToHtmlIfNeeded,
  qtFontString,
  removeIndented,
  replaceIndented,
  serializeXml,
  setAttrs,
  setText,
  subChildren,
  textOf,
  type XDocument,
  type XElement,
} from "./xml";

/** Diagram::margin — offset of the folio border in QET scene coordinates. */
export const QET_MARGIN = 5;
/** Conductor::extendTerminal default and Diagram::xGrid / yGrid. */
const EXTEND = 10;
const GRID = 10;
/** Header sizes are not stored in .qet files (BorderProperties defaults). */
const HEADER = 20;

/* ------------------------------------------------------------------ */
/* Junction definition written by Volt                                  */
/* ------------------------------------------------------------------ */

export const JUNCTION_DEF_PATH = "embed://import/volt/volt_junction.elmt";
export const JUNCTION_DEF_NAME = "volt_junction";
export const JUNCTION_MARKER = "volt:junction";
const JUNCTION_DEF_UUID = "5e0a1c3b-7d2f-4e8a-9b1c-766f6c740001";
const JUNCTION_PIN_UUID = "5e0a1c3b-7d2f-4e8a-9b1c-766f6c740002";

/** A tiny element: one terminal docked at the hotspot and a filled dot, so several conductors can meet. */
export function junctionDef(): ElementDef {
  const style = { lineStyle: "normal", lineWeight: "none", filling: "black", color: "black" } as const;
  return {
    id: JUNCTION_DEF_PATH,
    uuid: JUNCTION_DEF_UUID,
    name: JUNCTION_DEF_NAME,
    names: { en: JUNCTION_DEF_NAME },
    width: 10,
    height: 10,
    hotspotX: 5,
    hotspotY: 5,
    linkType: "simple",
    prefix: "",
    category: "volt",
    prims: [{ t: "ellipse", x: -2.5, y: -2.5, w: 5, h: 5, style: { ...style } }],
    pins: [{ id: JUNCTION_PIN_UUID, x: 0, y: 0, orient: "n", name: "", number: "", type: "Generic" }],
    info: {},
    kind: {},
    meta: { informations: `${JUNCTION_MARKER} — conductor junction generated by Volt` },
  };
}

/** Recognise the junction definition written by exportQet (informations carry the marker). */
const isJunctionDef = (d: ElementDef | undefined) => !!d && d.linkType === "simple" && (d.meta.informations ?? "").includes(JUNCTION_MARKER);

/* ------------------------------------------------------------------ */
/* Report                                                               */
/* ------------------------------------------------------------------ */

class Reporter {
  private items = new Map<string, CompatItem>();
  add(level: CompatLevel, area: string, message: string, count = 1, page?: string): void {
    const key = `${level}\u0000${area}\u0000${message}\u0000${page ?? ""}`;
    const it = this.items.get(key);
    if (it) it.count = (it.count ?? 0) + count;
    else this.items.set(key, { level, area, message, count, ...(page !== undefined ? { page } : {}) });
  }
  list(): CompatItem[] {
    const order: CompatLevel[] = ["supported", "degraded", "preserved", "unsupported"];
    return [...this.items.values()].sort((a, b) => order.indexOf(a.level) - order.indexOf(b.level));
  }
}

function makeReport(doc: Doc, source: string, qetVersion: string, r: Reporter): CompatReport {
  let elementCount = 0;
  let wireCount = 0;
  for (const p of doc.pages) {
    elementCount += p.elements.length;
    wireCount += p.wires.length;
  }
  return {
    source,
    qetVersion,
    pageCount: doc.pages.length,
    elementCount,
    wireCount,
    definitionCount: Object.keys(doc.defs).length,
    items: r.list(),
    createdAt: new Date().toISOString(),
  };
}

/* ------------------------------------------------------------------ */
/* Geometry helpers                                                     */
/* ------------------------------------------------------------------ */

const EPS = 1e-6;
const samePt = (a: Pt, b: Pt, eps = EPS) => Math.abs(a.x - b.x) <= eps && Math.abs(a.y - b.y) <= eps;
const shift = (p: Pt, d: number): Pt => ({ x: p.x + d, y: p.y + d });

/** Remove duplicate consecutive points and interior points of straight same-direction runs. */
export function normalizePath(pts: Pt[]): Pt[] {
  const out: Pt[] = [];
  for (const p of pts) if (!out.length || !samePt(out[out.length - 1], p)) out.push({ x: p.x, y: p.y });
  if (out.length < 3) return out;
  const res: Pt[] = [out[0]];
  for (let i = 1; i < out.length - 1; i++) {
    const a = res[res.length - 1];
    const b = out[i];
    const c = out[i + 1];
    const cross = (b.x - a.x) * (c.y - b.y) - (b.y - a.y) * (c.x - b.x);
    const dot = (b.x - a.x) * (c.x - b.x) + (b.y - a.y) * (c.y - b.y);
    if (Math.abs(cross) <= EPS && dot > 0) continue; // b lies on a straight run a->c
    res.push(b);
  }
  res.push(out[out.length - 1]);
  return res;
}

/** std::round (half away from zero) */
const stdRound = (v: number) => (v < 0 ? -Math.round(-v) : Math.round(v));
/** qRound(double) -> int */
const qRound = (v: number) => (v >= 0 ? Math.floor(v + 0.5) : Math.ceil(v - 0.5));

/** Conductor::extendTerminal() */
function extendTerminal(p: Pt, o: Orient): Pt {
  switch (o) {
    case "n":
      return { x: p.x, y: stdRound((p.y - EXTEND) / 10) * 10 };
    case "e":
      return { x: stdRound((p.x + EXTEND) / 10) * 10, y: p.y };
    case "s":
      return { x: p.x, y: stdRound((p.y + EXTEND) / 10) * 10 };
    default:
      return { x: stdRound((p.x - EXTEND) / 10) * 10, y: p.y };
  }
}

/** Grid-snapped midpoint as computed by the "cas 3/4" bridges (int maths + walk down to grid). */
function bridgeCoord(a: number, b: number): number {
  let v = Math.trunc(qRound(a + b) / 2);
  while (v % GRID !== 0) v--;
  return v === 0 ? 0 : v;
}

/**
 * Port of Conductor::generateConductorPath() (conductor.cpp, including the #734 fix that skips
 * degenerate bridges). Input and output are QET scene coordinates; the result goes from p1 to p2.
 */
export function qetAutoPath(p1: Pt, o1: Orient, p2: Pt, o2: Orient): Pt[] {
  const newp1 = extendTerminal(p1, o1);
  const newp2 = extendTerminal(p2, o2);
  let depart: Pt, arrivee: Pt, depart0: Pt, arrivee0: Pt, od: Orient, oa: Orient;
  if (newp1.x <= newp2.x) {
    [depart, arrivee, depart0, arrivee0, od, oa] = [newp1, newp2, p1, p2, o1, o2];
  } else {
    [depart, arrivee, depart0, arrivee0, od, oa] = [newp2, newp1, p2, p1, o2, o1];
  }
  const pts: Pt[] = [depart0, depart];
  if (depart.y < arrivee.y) {
    // descending path
    if ((od === "n" && (oa === "s" || oa === "w")) || (od === "e" && oa === "w")) {
      if (qRound(depart.x) !== qRound(arrivee.x)) {
        const x = bridgeCoord(depart.x, arrivee.x);
        pts.push({ x, y: depart.y }, { x, y: arrivee.y });
      }
    } else if ((od === "s" && (oa === "n" || oa === "e")) || (od === "w" && oa === "e")) {
      if (qRound(depart.y) !== qRound(arrivee.y)) {
        const y = bridgeCoord(depart.y, arrivee.y);
        pts.push({ x: depart.x, y }, { x: arrivee.x, y });
      }
    } else if ((od === "n" || od === "e") && (oa === "n" || oa === "e")) {
      pts.push({ x: arrivee.x, y: depart.y });
    } else {
      pts.push({ x: depart.x, y: arrivee.y });
    }
  } else {
    // ascending path
    if ((od === "w" && (oa === "e" || oa === "s")) || (od === "n" && oa === "s")) {
      if (qRound(depart.y) !== qRound(arrivee.y)) {
        const y = bridgeCoord(depart.y, arrivee.y);
        pts.push({ x: depart.x, y }, { x: arrivee.x, y });
      }
    } else if ((od === "e" && (oa === "w" || oa === "n")) || (od === "s" && oa === "n")) {
      if (qRound(depart.x) !== qRound(arrivee.x)) {
        const x = bridgeCoord(depart.x, arrivee.x);
        pts.push({ x, y: depart.y }, { x, y: arrivee.y });
      }
    } else if ((od === "w" || od === "n") && (oa === "w" || oa === "n")) {
      pts.push({ x: depart.x, y: arrivee.y });
    } else {
      pts.push({ x: arrivee.x, y: depart.y });
    }
  }
  pts.push(arrivee, arrivee0);
  return newp1.x > newp2.x ? pts.reverse() : pts;
}

type Segment = { horizontal: boolean; length: number };

function readSegments(c: XElement): Segment[] {
  const out: Segment[] = [];
  for (const s of children(c, "segment")) {
    // Conductor::pathFromXml(): segments without a numeric length are ignored
    const len = optNum(s, "length");
    if (len === undefined) continue;
    out.push({ horizontal: attr(s, "orientation") === "horizontal", length: len });
  }
  return out;
}

/**
 * Absolute conductor points (QET scene coords) as QET would build them.
 * Returns `auto: true` when QET falls back to generateConductorPath.
 */
function conductorPoints(segs: Segment[], t1: Pt, o1: Orient, t2: Pt, o2: Orient): { pts: Pt[]; auto: boolean; inconsistent: boolean } {
  if (!segs.length) return { pts: qetAutoPath(t1, o1, t2, o2), auto: true, inconsistent: false };
  let w = 0;
  let h = 0;
  for (const s of segs) {
    if (s.horizontal) w += s.length;
    else h += s.length;
  }
  if (Math.abs(t2.x - t1.x - w) > 1 || Math.abs(t2.y - t1.y - h) > 1) {
    return { pts: qetAutoPath(t1, o1, t2, o2), auto: true, inconsistent: true };
  }
  const pts: Pt[] = [{ ...t1 }];
  for (const s of segs) {
    const last = pts[pts.length - 1];
    pts.push(s.horizontal ? { x: last.x + s.length, y: last.y } : { x: last.x, y: last.y + s.length });
  }
  return { pts, auto: false, inconsistent: false };
}

/** Orthogonal segments for a polyline (diagonals are split horizontal-then-vertical). */
function pointsToSegments(pts: Pt[]): Segment[] {
  const segs: Segment[] = [];
  for (let i = 1; i < pts.length; i++) {
    const a = pts[i - 1];
    const b = pts[i];
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    if (Math.abs(dx) > EPS) segs.push({ horizontal: true, length: dx });
    if (Math.abs(dy) > EPS) segs.push({ horizontal: false, length: dy });
  }
  return segs;
}

const polyEq = (a: Pt[], b: Pt[], eps = 0.01) => a.length === b.length && a.every((p, i) => samePt(p, b[i], eps));

/* ------------------------------------------------------------------ */
/* Misc helpers                                                         */
/* ------------------------------------------------------------------ */

/** QET version "0.100.0-dev" / "0.80" / "0.3" -> comparable number (0.x minor as decimal fraction). */
export function qetVersionNumber(v: string): number {
  const m = /^(\d+)\.(\d+)/.exec(v.trim());
  if (!m) return 0;
  const major = parseInt(m[1], 10);
  let minor = parseInt(m[2], 10);
  if (m[2].length === 1) minor *= 10; // "0.7" == "0.70", "0.65" < "0.7"
  return major * 1000 + minor;
}
const UUID_REFS_SINCE = qetVersionNumber("0.7");

function diagramNodes(root: XElement): XElement[] {
  // QETProject::readDiagramsXml() takes every <diagram> in document order
  const list = root.getElementsByTagName("diagram");
  const out: XElement[] = [];
  for (let i = 0; i < list.length; i++) {
    const d = list.item(i);
    if (d) out.push(d);
  }
  return out;
}

function contextMap(container: XElement | null, tag: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const p of children(container, tag)) {
    const n = attr(p, "name");
    if (n) out[n] = textOf(p);
  }
  return out;
}

function roleForInfo(info: string | null): TextRole {
  if (info === "label" || info === "formula") return "componentRef";
  if (info === "comment" || info === "description") return "componentName";
  return "annotation";
}

const TB_FIELDS = ["author", "date", "title", "filename", "plant", "locmach", "indexrev", "version", "folio", "auto_page_num"] as const;
/**
 * Custom title block properties (<diagram><properties><property name>) share Page.titleBlock.fields
 * with the built-in attributes; a custom property whose name collides with a built-in field is
 * stored under this prefix so neither is lost.
 */
const CUSTOM_PREFIX = "custom:";
const isBuiltinField = (k: string) => (TB_FIELDS as readonly string[]).includes(k);
const customKey = (name: string) => (isBuiltinField(name) || name.startsWith(CUSTOM_PREFIX) ? CUSTOM_PREFIX + name : name);
const customName = (key: string) => (key.startsWith(CUSTOM_PREFIX) ? key.slice(CUSTOM_PREFIX.length) : key);

const basename = (f: string) => (f.split(/[\\/]/).pop() ?? f).replace(/\.qet$/i, "");

type ResolvedPin = { el: string; pin: string; junction?: string };
type InstRec = { kind: "elem"; inst: ElemInst; def: ElementDef } | { kind: "junction"; j: Junction; def: ElementDef };

/* ------------------------------------------------------------------ */
/* IMPORT                                                               */
/* ------------------------------------------------------------------ */

type ImportCtx = {
  doc: Doc;
  /** embedded junction definitions (kept out of doc.defs) */
  junctionDefs: Map<string, ElementDef>;
  rep: Reporter;
  preserved: Map<string, number>;
  version: string;
};

function tallyPreserved(ctx: ImportCtx, where: string, tag: string, n = 1) {
  const k = `${where}\u0000<${tag}>`;
  ctx.preserved.set(k, (ctx.preserved.get(k) ?? 0) + n);
}

function readCollection(ctx: ImportCtx, root: XElement): void {
  let coll = child(root, "collection");
  if (!coll) {
    const all = root.getElementsByTagName("collection");
    coll = all.length ? all.item(0) : null;
  }
  if (!coll) return;
  const walk = (cat: XElement, path: string[]) => {
    for (const c of children(cat)) {
      if (c.tagName === "category") walk(c, [...path, attr(c, "name")]);
      else if (c.tagName === "element") {
        const name = attr(c, "name");
        const key = `embed://${[...path, name].join("/")}`;
        const defEl = child(c, "definition");
        if (!defEl) {
          ctx.rep.add("degraded", "definitions", "embedded element without <definition> (instances drawn as placeholders)");
          continue;
        }
        try {
          const def = parseElmtNode(defEl, { id: key, category: path.slice(1).join("/") }, serializeXml(defEl));
          if (isJunctionDef(def)) ctx.junctionDefs.set(key, def);
          else ctx.doc.defs[key] = def;
        } catch (e) {
          ctx.rep.add("degraded", "definitions", `unreadable embedded definition ${key}: ${(e as Error).message}`);
        }
      } else if (c.tagName !== "names") tallyPreserved(ctx, "collection", c.tagName);
    }
  };
  walk(coll, []);
}

function readTitleBlocks(ctx: ImportCtx, root: XElement): void {
  for (const t of subChildren(root, "titleblocktemplates", "titleblocktemplate")) {
    try {
      const tpl = parseTitleBlockNode(t);
      ctx.doc.titleBlocks[tpl.name] = tpl;
      ctx.rep.add("supported", "title blocks", "embedded title block templates");
    } catch (e) {
      ctx.rep.add("degraded", "title blocks", `unparseable title block template "${attr(t, "name")}" — default used`);
      tallyPreserved(ctx, "titleblocktemplates", "titleblocktemplate");
    }
  }
}

/** Placeholder definition for a missing element definition, built from an instance's terminals. */
function placeholderDef(defId: string, elNode: XElement): ElementDef {
  const pins: PinDef[] = [];
  for (const t of subChildren(elNode, "terminals", "terminal")) {
    const o = ORIENT_FROM_INDEX[int(t, "orientation", 0)] ?? "n";
    const off = dockElmtOffset(o);
    pins.push({ id: `t${pins.length}`, x: num(t, "x") - off.x, y: num(t, "y") - off.y, orient: o, name: "", number: "", type: "Generic" });
  }
  const bb = primsBBox({ prims: [], pins }) ?? { x: -10, y: -10, w: 20, h: 20 };
  const x0 = Math.floor((bb.x - 5) / 10) * 10;
  const y0 = Math.floor((bb.y - 5) / 10) * 10;
  const x1 = Math.max(x0 + 20, Math.ceil((bb.x + bb.w + 5) / 10) * 10);
  const y1 = Math.max(y0 + 20, Math.ceil((bb.y + bb.h + 5) / 10) * 10);
  const name = defId.split("/").pop()?.replace(/\.elmt$/i, "") || defId;
  return {
    id: defId,
    uuid: "",
    name,
    names: { en: name },
    width: x1 - x0,
    height: y1 - y0,
    hotspotX: -x0,
    hotspotY: -y0,
    linkType: "simple",
    prefix: "",
    category: "",
    prims: [{ t: "rect", x: x0, y: y0, w: x1 - x0, h: y1 - y0, rx: 0, ry: 0, style: { lineStyle: "dashed", lineWeight: "thin", filling: "none", color: "red" } }],
    pins,
    info: {},
    kind: {},
    meta: { missing: defId },
    placeholder: true,
  };
}

/** Map instance <terminals> entries (numeric ids) to definition pins by stub position + orientation. */
function matchInstanceTerminals(elNode: XElement, def: ElementDef, grow: boolean): Map<number, string> {
  const map = new Map<number, string>();
  const used = new Set<string>();
  for (const t of subChildren(elNode, "terminals", "terminal")) {
    const id = int(t, "id", NaN);
    const o = ORIENT_FROM_INDEX[int(t, "orientation", 0)] ?? "n";
    const tx = num(t, "x");
    const ty = num(t, "y");
    let pin = def.pins.find((p) => {
      if (used.has(p.id) || p.orient !== o) return false;
      const off = dockElmtOffset(p.orient);
      return Math.abs(p.x + off.x - tx) < 0.01 && Math.abs(p.y + off.y - ty) < 0.01;
    });
    if (!pin && grow) {
      const off = dockElmtOffset(o);
      pin = { id: `t${def.pins.length}`, x: tx - off.x, y: ty - off.y, orient: o, name: "", number: "", type: "Generic" };
      def.pins.push(pin);
    }
    if (!pin) continue;
    used.add(pin.id);
    if (Number.isFinite(id)) map.set(id, pin.id);
  }
  return map;
}

function textOverride(size: number | undefined, rotation: number, color: string | undefined, halign?: "left" | "center" | "right"): Partial<TextStyle> | undefined {
  const o: Partial<TextStyle> = {};
  if (size !== undefined) o.size = size;
  if (rotation) o.rotation = rotation;
  if (color) o.color = color;
  if (halign && halign !== "left") o.align = halign;
  return Object.keys(o).length ? o : undefined;
}

function readElementTexts(ctx: ImportCtx, elNode: XElement, def: ElementDef, inst: ElemInst, pageTitle: string): void {
  const dyn = subChildren(elNode, "dynamic_texts", "dynamic_elmt_text");
  for (const d of dyn) {
    const tf = attr(d, "text_from", "UserText");
    const infoName = child(d, "info_name");
    const info = tf === "ElementInfo" ? textOf(infoName) || null : null;
    if (tf === "CompositeText") ctx.rep.add("degraded", "texts", "composite element texts shown with their last computed value", 1, pageTitle);
    const font = parseQtFont(optAttr(d, "font"));
    const colorEl = child(d, "color");
    const uuid = normUuid(optAttr(d, "uuid"));
    const t: PlacedText = {
      id: uuid || uid(),
      role: roleForInfo(info),
      info,
      text: textOf(child(d, "text")),
      x: num(d, "x"),
      y: num(d, "y"),
    };
    const ov = textOverride(font.size ?? optNum(d, "font_size"), num(d, "rotation"), colorEl ? textOf(colorEl) : undefined, halignFromQet(optAttr(d, "Halignment")));
    if (ov) t.override = ov;
    if (uuid) t.uuid = uuid;
    inst.texts.push(t);
  }
  if (dyn.length) return;

  const legacy = legacyInstanceTexts(elNode, def);
  if (!legacy.texts.length) return;
  for (const [k, v] of Object.entries(legacy.info)) if (inst.info[k] === undefined) inst.info[k] = v;
  for (const lt of legacy.texts) {
    const id = uid();
    inst.texts.push({ ...lt, id, uuid: id });
  }
  ctx.rep.add("degraded", "texts", "pre-0.7 element text fields converted to dynamic texts", legacy.texts.length, pageTitle);
}

/**
 * Pre-0.7 instance texts: <inputs><input x y text [userx usery]/> matching the definition's legacy
 * <input> fields (middle-left anchored, see Element::parseInput). Modern QET ignores them; Volt
 * shows them as placed texts. Deterministic, so the exporter can tell whether they were edited.
 */
function legacyInstanceTexts(elNode: XElement, def: ElementDef): { texts: Omit<PlacedText, "id">[]; info: Record<string, string> } {
  const texts: Omit<PlacedText, "id">[] = [];
  const info: Record<string, string> = {};
  if (subChildren(elNode, "dynamic_texts", "dynamic_elmt_text").length) return { texts, info };
  const defTexts = def.prims.filter((p): p is Extract<typeof p, { t: "dyntext" }> => p.t === "dyntext");
  subChildren(elNode, "inputs", "input").forEach((inp, i) => {
    const x = num(inp, "x");
    const y = num(inp, "y");
    const match =
      defTexts.find((p) => {
        const tl = legacyInputToTopLeft(x, y, p.size, p.rotation);
        return Math.abs(tl.x - p.x) < 0.5 && Math.abs(tl.y - p.y) < 0.5;
      }) ?? defTexts[i];
    const size = match?.size ?? 9;
    const rotation = num(inp, "rotation", match?.rotation ?? 0);
    const pos = legacyInputToTopLeft(num(inp, "userx", x), num(inp, "usery", y), size, rotation);
    const text = attr(inp, "text");
    const infoName = match?.from === "ElementInfo" ? (match.info ?? null) : null;
    if (infoName && text && info[infoName] === undefined) info[infoName] = text;
    const t: Omit<PlacedText, "id"> = { role: roleForInfo(infoName), info: infoName, text, x: pos.x, y: pos.y };
    const ov = textOverride(size, rotation, undefined);
    if (ov) t.override = ov;
    texts.push(t);
  });
  return { texts, info };
}

const sameLegacy = (a: Omit<PlacedText, "id">[], b: PlacedText[]) =>
  a.length === b.length &&
  a.every((t, i) => {
    const o = b[i];
    return o.info === t.info && o.text === t.text && o.x !== null && o.y !== null && Math.abs(o.x - (t.x ?? 0)) < 1e-6 && Math.abs(o.y - (t.y ?? 0)) < 1e-6 && stableStringify(o.override ?? {}) === stableStringify(t.override ?? {});
  });

const ELEMENT_MODELED = new Set(["terminals", "elementInformations", "dynamic_texts", "inputs"]);
const CONDUCTOR_MODELED = new Set(["segment"]);
const DIAGRAM_MODELED = new Set(["elements", "conductors", "inputs", "properties"]);
const PROJECT_MODELED = new Set(["properties", "diagram", "collection", "titleblocktemplates"]);

function tallyChildren(ctx: ImportCtx, where: string, el: XElement, modeled: Set<string>) {
  for (const c of children(el)) {
    if (modeled.has(c.tagName)) continue;
    // empty standard containers carry nothing worth reporting
    const nAttrs = Object.keys(allAttrs(c)).length;
    if (!nAttrs && !children(c).length && !textOf(c).trim()) continue;
    tallyPreserved(ctx, where, c.tagName);
  }
}

function readShapes(diag: XElement, page: Page, ctx: ImportCtx): void {
  const dash = (s: string): Shape["dash"] => (s === "DashLine" ? "dashed" : s === "DotLine" ? "dotted" : s === "DashDotLine" || s === "DashDotDotLine" ? "dashdot" : "solid");
  subChildren(diag, "shapes", "shape").forEach((s, idx) => {
    const type = attr(s, "type");
    const pen = child(s, "pen");
    const brush = child(s, "brush");
    const p1 = { x: num(s, "x1") - QET_MARGIN, y: num(s, "y1") - QET_MARGIN };
    const p2 = { x: num(s, "x2") - QET_MARGIN, y: num(s, "y2") - QET_MARGIN };
    let kind: Shape["kind"];
    let pts: Pt[];
    if (type === "Line") [kind, pts] = ["line", [p1, p2]];
    else if (type === "Rectangle") [kind, pts] = ["rect", [p1, p2]];
    else if (type === "Ellipse") [kind, pts] = ["ellipse", [p1, p2]];
    else if (type === "Polygon") {
      kind = "polygon";
      pts = subChildren(s, "points", "point").map((p) => ({ x: num(p, "x") - QET_MARGIN, y: num(p, "y") - QET_MARGIN }));
    } else {
      kind = "polygon";
      pts = subChildren(s, "nodes", "node").map((p) => ({ x: num(p, "x") - QET_MARGIN, y: num(p, "y") - QET_MARGIN }));
      ctx.rep.add("degraded", "shapes", `shape type "${type || "?"}" drawn as polygon (curves not rendered)`, 1, page.title);
    }
    const bstyle = brush ? attr(brush, "style", "NoBrush") : "NoBrush";
    page.shapes.push({
      id: uid(),
      kind,
      pts,
      color: pen ? attr(pen, "color", "#000000") : "#000000",
      width: pen ? num(pen, "widthF", 1) : 1,
      dash: dash(pen ? attr(pen, "style", "DashLine") : "DashLine"),
      fill: bstyle !== "NoBrush" && brush ? attr(brush, "color", "#000000") : null,
      qet: { idx },
    });
  });
  if (page.shapes.length) ctx.rep.add("preserved", "shapes", "drawing shapes (read-only, kept as-is on export)", page.shapes.length, page.title);
}

function importDiagram(ctx: ImportCtx, diag: XElement, di: number): Page {
  const { doc, rep } = ctx;
  const title = attr(diag, "title");
  const page = newPage(di, title);
  page.title = title;
  page.qet = { idx: di };
  page.meta = {};
  const duuid = normUuid(optAttr(diag, "uuid"));
  if (duuid) page.id = duuid;

  // border (BorderTitleBlock::borderFromXml)
  const b = page.border;
  b.cols = int(diag, "cols", b.cols);
  b.colW = num(diag, "colsize", b.colW);
  if (diag.hasAttribute("rows") && diag.hasAttribute("rowsize")) {
    b.rows = int(diag, "rows", b.rows);
    b.rowH = num(diag, "rowsize", b.rowH);
  } else if (diag.hasAttribute("height")) {
    b.rows = Math.max(3, Math.round((num(diag, "height") - HEADER) / b.rowH));
  }
  b.showCols = attr(diag, "displaycols") !== "false";
  b.showRows = attr(diag, "displayrows") !== "false";
  b.headerW = HEADER;
  b.headerH = HEADER;

  // title block (TitleBlockProperties::fromXml)
  const fields: Record<string, string> = {};
  for (const f of TB_FIELDS) if (diag.hasAttribute(f)) fields[f] = attr(diag, f);
  fields.title = title;
  for (const [k, v] of Object.entries(contextMap(child(diag, "properties"), "property"))) fields[customKey(k)] = v;
  page.titleBlock = { show: true, template: DEFAULT_TB, fields };
  const tplName = optAttr(diag, "titleblocktemplate");
  if (tplName) {
    const coll = attr(diag, "titleblocktemplateCollection", "common");
    if (coll === "embedded" && doc.titleBlocks[tplName]?.xml) page.titleBlock.template = tplName;
    else if (tplName !== "default" || coll === "embedded") {
      page.meta["qet:titleblocktemplate"] = `${coll}:${tplName}`;
      rep.add("degraded", "title blocks", `title block template "${tplName}" (${coll}) not available — default used`, 1, title);
    }
  }
  rep.add("supported", "title blocks", "folio title blocks");

  /* ---------------- elements ---------------- */
  const byUuid = new Map<string, InstRec>();
  const byNumericId = new Map<number, ResolvedPin>();
  const keepElements: number[] = [];
  const placeholders = new Map<string, number>();
  const linkTypes = new Map<string, number>();

  subChildren(diag, "elements", "element").forEach((el, idx) => {
    const type = optAttr(el, "type");
    // Element::valideXml(): type, x and y are mandatory
    if (!type || optNum(el, "x") === undefined || optNum(el, "y") === undefined) {
      keepElements.push(idx);
      rep.add("degraded", "elements", "invalid element instance (ignored by QET too) — kept in file, not shown", 1, title);
      return;
    }
    const jdef = ctx.junctionDefs.get(type);
    let def = jdef ?? doc.defs[type];
    if (!def) {
      def = placeholderDef(type, el);
      doc.defs[type] = def;
    }
    if (def.placeholder) placeholders.set(type, (placeholders.get(type) ?? 0) + 1);
    const ruuid = normUuid(optAttr(el, "uuid"));
    const x = num(el, "x") - QET_MARGIN;
    const y = num(el, "y") - QET_MARGIN;
    const numeric = matchInstanceTerminals(el, def, !!def.placeholder);

    if (jdef) {
      const j: Junction = { id: ruuid || uid(), x, y };
      if (ruuid) j.qetElemId = ruuid;
      page.junctions.push(j);
      const rec: InstRec = { kind: "junction", j, def };
      if (ruuid) byUuid.set(ruuid, rec);
      for (const [n] of numeric) byNumericId.set(n, { el: j.id, pin: JUNCTION_PIN_UUID, junction: j.id });
      return;
    }

    const ori = int(el, "orientation", 0);
    const inst: ElemInst = {
      id: ruuid || uid(),
      defId: type,
      x,
      y,
      rot: (ori >= 0 && ori <= 3 ? ori : 0) as ElemInst["rot"],
      mirror: false,
      info: contextMap(child(el, "elementInformations"), "elementInformation"),
      texts: [],
      qet: { idx, terminalIds: {} },
    };
    const z = optNum(el, "z");
    if (z !== undefined) inst.z = z;
    if (attr(el, "is_movable", "1") === "0" || attr(el, "is_movable") === "false") inst.locked = true;
    if (el.hasAttribute("freezeLabel")) inst.refLocked = attr(el, "freezeLabel") === "true";
    for (const [n, pinId] of numeric) {
      inst.qet!.terminalIds![pinId] = String(n);
      byNumericId.set(n, { el: inst.id, pin: pinId });
    }
    const prefix = attr(el, "prefix");
    if (prefix && !def.prefix && !def.placeholder) def.prefix = prefix;
    readElementTexts(ctx, el, def, inst, title);
    // cross-reference links (the original <links_uuids> node stays in the preserved XML)
    const links = children(child(el, "links_uuids"), "link_uuid").map((l) => normUuid(attr(l, "uuid"))).filter(Boolean);
    if (links.length) inst.links = links;
    page.elements.push(inst);
    if (ruuid) byUuid.set(ruuid, { kind: "elem", inst, def });
    if (["master", "slave", "next_report", "previous_report"].includes(def.linkType)) linkTypes.set(def.linkType, (linkTypes.get(def.linkType) ?? 0) + 1);
    if (children(child(el, "links_uuids"), "link_uuid").length) tallyPreserved(ctx, "element", "links_uuids");
    tallyChildren(ctx, "element", el, new Set([...ELEMENT_MODELED, "links_uuids"]));
  });
  if (keepElements.length) page.meta["qet:keepElements"] = keepElements.join(",");
  for (const [type, n] of placeholders) rep.add("degraded", "definitions", `missing definition ${type} — drawn as placeholder box`, n, title);
  for (const [lt, n] of linkTypes) {
    const what = lt.endsWith("report") ? "folio report arrows" : "master/slave cross-referenced elements";
    rep.add("degraded", "elements", `${what} (${lt}): links are followed when clicked (editor and PDF); editing links is not supported`, n, title);
  }
  const elemCount = page.elements.length;
  if (elemCount) rep.add("supported", "elements", "element instances", elemCount, title);
  if (page.junctions.length) rep.add("supported", "junctions", "Volt junctions restored", page.junctions.length, title);

  /* ---------------- conductors ---------------- */
  const elemById = new Map(page.elements.map((e) => [e.id, e]));
  const junctionById = new Map(page.junctions.map((j) => [j.id, j]));
  const keepConductors: number[] = [];
  let autoRouted = 0;
  let inconsistent = 0;

  const resolve = (c: XElement, n: 1 | 2): ResolvedPin | null => {
    const eAttr = optAttr(c, `element${n}`);
    if (eAttr !== undefined) {
      const rec = byUuid.get(normUuid(eAttr));
      if (!rec) return null;
      const tid = normUuid(optAttr(c, `terminal${n}`));
      const pin = rec.def.pins.find((p) => p.id === tid);
      if (!pin) return null;
      return rec.kind === "junction" ? { el: rec.j.id, pin: pin.id, junction: rec.j.id } : { el: rec.inst.id, pin: pin.id };
    }
    const id = int(c, `terminal${n}`, NaN);
    return Number.isFinite(id) ? (byNumericId.get(id) ?? null) : null;
  };
  /** scene dock point (QET coords) + scene orientation of a resolved end */
  const dockOf = (r: ResolvedPin): { p: Pt; o: Orient } | null => {
    if (r.junction) {
      const j = junctionById.get(r.junction);
      return j ? { p: shift(j, QET_MARGIN), o: "n" } : null;
    }
    const inst = elemById.get(r.el);
    const def = inst && doc.defs[inst.defId];
    const pin = def?.pins.find((p) => p.id === r.pin);
    if (!inst || !pin) return null;
    const q = { x: inst.x + QET_MARGIN, y: inst.y + QET_MARGIN, rot: inst.rot, mirror: false };
    return { p: toScene(q, pin), o: rotOrient(pin.orient, inst.rot, false) };
  };
  const endOf = (r: ResolvedPin): WireEnd => (r.junction ? { k: "junction", j: r.junction } : { k: "pin", el: r.el, pin: r.pin });

  subChildren(diag, "conductors", "conductor").forEach((c, idx) => {
    const r1 = c.hasAttribute("terminal1") && c.hasAttribute("terminal2") ? resolve(c, 1) : null;
    const r2 = r1 ? resolve(c, 2) : null;
    const d1 = r1 && dockOf(r1);
    const d2 = r2 && dockOf(r2);
    if (!r1 || !r2 || !d1 || !d2 || (r1.el === r2.el && r1.pin === r2.pin)) {
      keepConductors.push(idx);
      rep.add("degraded", "conductors", "conductor referencing a missing terminal — kept in file, not shown", 1, title);
      return;
    }
    const geo = conductorPoints(readSegments(c), d1.p, d1.o, d2.p, d2.o);
    if (geo.auto) autoRouted++;
    if (geo.inconsistent) inconsistent++;
    const attrs = allAttrs(c);
    const w: Wire = {
      id: normUuid(attrs.uuid) || uid(),
      a: endOf(r1),
      b: endOf(r2),
      pts: normalizePath(geo.pts.map((p) => shift(p, -QET_MARGIN))),
      qet: { idx, attrs },
    };
    if (attrs.num) w.label = attrs.num;
    if (attrs.cable) w.cable = attrs.cable;
    page.wires.push(w);
    tallyChildren(ctx, "conductor", c, CONDUCTOR_MODELED);
  });
  if (keepConductors.length) page.meta["qet:keepConductors"] = keepConductors.join(",");
  if (page.wires.length) rep.add("supported", "conductors", "conductors", page.wires.length, title);
  if (autoRouted - inconsistent) rep.add("supported", "conductors", "conductors without stored path auto-routed like QET", autoRouted - inconsistent, title);
  if (inconsistent) rep.add("degraded", "conductors", "conductor path inconsistent with its terminals — auto-routed like QET", inconsistent, title);

  /* ---------------- independent texts ---------------- */
  subChildren(diag, "inputs", "input").forEach((t, idx) => {
    const font = parseQtFont(optAttr(t, "font"));
    const ft: FreeText = {
      id: uid(),
      x: num(t, "x") - QET_MARGIN,
      y: num(t, "y") - QET_MARGIN,
      text: htmlToPlain(attr(t, "text")),
      role: "annotation",
      qet: { idx },
    };
    const ov = textOverride(font.size, num(t, "rotation"), undefined);
    if (ov) ft.override = ov;
    page.texts.push(ft);
  });
  const textCount = page.texts.length + page.elements.reduce((n, e) => n + e.texts.length, 0);
  if (textCount) rep.add("supported", "texts", "texts (element and independent)", textCount, title);

  readShapes(diag, page, ctx);
  tallyChildren(ctx, "diagram", diag, new Set([...DIAGRAM_MODELED, "shapes"]));
  return page;
}

/**
 * Import a QElectroTech project. Never drops data silently: everything that is not modelled is
 * listed in the report and preserved in `doc.qet.source` for the patching exporter.
 */
export function importQet(xml: string, filename: string): { doc: Doc; report: CompatReport } {
  const xdoc = parseXml(xml);
  const root = xdoc.documentElement as XElement;
  if (root.tagName !== "project") throw new Error(`not a QElectroTech project (root <${root.tagName}>)`);
  const version = attr(root, "version");
  const doc = newDoc(attr(root, "title") || basename(filename));
  doc.pages = [];
  doc.meta.props = contextMap(child(root, "properties"), "property");
  doc.qet = { version, source: xml, filename };
  const ctx: ImportCtx = { doc, junctionDefs: new Map(), rep: new Reporter(), preserved: new Map(), version };

  readCollection(ctx, root);
  const embeddedDefs = Object.keys(doc.defs).length;
  if (embeddedDefs) ctx.rep.add("supported", "definitions", "embedded element definitions", embeddedDefs);
  readTitleBlocks(ctx, root);

  diagramNodes(root).forEach((d, i) => doc.pages.push(importDiagram(ctx, d, i)));
  if (!doc.pages.length) {
    ctx.rep.add("supported", "pages", "project without folios — an empty page was created");
    doc.pages.push(newPage(0));
  }

  tallyChildren(ctx, "project", root, PROJECT_MODELED);
  for (const [k, n] of ctx.preserved) {
    const [where, tag] = k.split("\u0000");
    ctx.rep.add("preserved", where, `${tag} kept untouched on export`, n);
  }
  return { doc, report: makeReport(doc, filename, version, ctx.rep) };
}

/* ------------------------------------------------------------------ */
/* EXPORT                                                               */
/* ------------------------------------------------------------------ */

const DEFAULT_CONDUCTOR_ATTRS: Record<string, string> = {
  num: "",
  bus: "",
  condsize: "1",
  conductor_color: "",
  "vertical-alignment": "AlignRight",
  conductor_section: "",
  function: "",
  type: "multi",
  vertirotatetext: "270",
  tension_protocol: "",
  "dash-size": "1",
  formula: "",
  color: "#000000",
  color2: "#000000",
  displaytext: "1",
  bicolor: "false",
  "horizontal-alignment": "AlignBottom",
  onetextperfolio: "0",
  numsize: "7",
  text_color: "#000000",
  cable: "",
  horizrotatetext: "0",
};

const IMPORT_NAMES: Record<string, string> = { en: "Imported elements", fr: "Éléments importés", de: "Importierte elemente" };

function skeletonProject(doc: Doc): string {
  const cond = Object.entries(DEFAULT_CONDUCTOR_ATTRS)
    .map(([k, v]) => ` ${k}="${v}"`)
    .join("");
  const names = Object.entries(IMPORT_NAMES)
    .map(([l, n]) => `<name lang="${l}">${n}</name>`)
    .join("");
  const x = `<project version="${QET_VERSION}" title="">
<properties/>
<newdiagrams>
<border cols="17" colsize="60" displaycols="true" rows="8" rowsize="80" displayrows="true"/>
<inset author="" title="" filename="" plant="" locmach="" indexrev="" version="" folio="%id/%total" auto_page_num="" date="null" displayAt="bottom"/>
<conductors${cond}/>
<report label="%f-%l%c"/>
<xrefs/>
<conductors_autonums current_autonum="" freeze_new_conductors="false" auto_break_conductors="false"/>
<folio_autonums/>
<element_autonums current_autonum="" freeze_new_elements="false"/>
</newdiagrams>
<collection><category name="import"><names>${names}</names></category></collection>
</project>`;
  const d = parseXml(x);
  const root = d.documentElement as XElement;
  root.setAttribute("title", doc.meta.title);
  formatSubtree(d, root, 0); // QDom-like layout
  return serializeXml(d);
}

type ExportCtx = {
  doc: Doc;
  x: XDocument;
  rep: Reporter;
  useUuidRefs: boolean;
  /** defId -> type path written in instances */
  typeOf: Map<string, string>;
  usedDefs: Set<string>;
  needJunctionDef: boolean;
};

const slug = (s: string) =>
  s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^A-Za-z0-9._-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase() || "element";

/** The `type` path an instance of `def` is written with (embedding non-embedded defs). */
function typePathFor(ctx: ExportCtx, defId: string): string {
  const known = ctx.typeOf.get(defId);
  if (known) return known;
  const def = ctx.doc.defs[defId];
  let path: string;
  if (!def || def.placeholder) path = defId; // external reference, QET resolves it from its libraries
  else if (defId.startsWith("embed://")) path = defId;
  else if (/^(common|custom|company):\/\//.test(defId)) path = `embed://import/${defId.replace(/^[a-z]+:\/\//, "")}`;
  else {
    const base = `embed://import/volt/${slug(def.name || defId)}`;
    const taken = new Set(ctx.typeOf.values());
    let p = `${base}.elmt`;
    for (let i = 2; taken.has(p) || (ctx.doc.defs[p] && p !== defId); i++) p = `${base}_${i}.elmt`;
    path = p;
  }
  if (!path.endsWith(".elmt") && path.startsWith("embed://")) path += ".elmt";
  ctx.typeOf.set(defId, path);
  return path;
}

/* ---------------- collection ---------------- */

function ensureCategory(ctx: ExportCtx, parent: XElement, name: string): XElement {
  const found = children(parent, "category").find((c) => attr(c, "name") === name);
  if (found) return found;
  const cat = createEl(ctx.x, "category", { name });
  const names = createEl(ctx.x, "names");
  const labels = name === "import" ? IMPORT_NAMES : { en: name };
  for (const [lang, v] of Object.entries(labels)) names.appendChild(createEl(ctx.x, "name", { lang }, [v]));
  cat.appendChild(names);
  // categories before elements, like XmlElementCollection
  const firstElement = children(parent, "element")[0] ?? null;
  return insertIndented(ctx.x, parent, cat, firstElement);
}

function putDefinition(ctx: ExportCtx, coll: XElement, path: string, def: ElementDef): void {
  const segs = path.replace(/^embed:\/\//, "").split("/").filter(Boolean);
  const file = segs.pop();
  if (!file || !segs.length) {
    ctx.rep.add("unsupported", "definitions", `invalid embedded path ${path}`);
    return;
  }
  let cat = coll;
  for (const s of segs) cat = ensureCategory(ctx, cat, s);
  const elNode = children(cat, "element").find((e) => attr(e, "name") === file);
  if (elNode) {
    const old = child(elNode, "definition");
    if (old) {
      try {
        const cur = parseElmtNode(old, { id: path, category: def.category });
        if (defSignature(cur) === defSignature(def)) return; // untouched, byte identical
      } catch {
        /* rewrite */
      }
      replaceIndented(ctx.x, old, definitionElement(ctx.x, def));
    } else insertIndented(ctx.x, elNode, definitionElement(ctx.x, def));
    ctx.rep.add("supported", "definitions", "modified definitions updated in the embedded collection");
    return;
  }
  const node = createEl(ctx.x, "element", { name: file }, [definitionElement(ctx.x, def)]);
  insertIndented(ctx.x, cat, node);
  ctx.rep.add("supported", "definitions", "definitions added to the embedded collection");
}

function writeCollection(ctx: ExportCtx, root: XElement): void {
  const coll = ensureChild(ctx.x, root, "collection");
  for (const defId of ctx.usedDefs) {
    const def = ctx.doc.defs[defId];
    if (!def) continue;
    if (def.placeholder) {
      ctx.rep.add("degraded", "definitions", `definition ${defId} unavailable — instances keep their external reference`);
      continue;
    }
    putDefinition(ctx, coll, typePathFor(ctx, defId), def);
  }
  if (ctx.needJunctionDef) {
    const jd = junctionDef();
    putDefinition(ctx, coll, JUNCTION_DEF_PATH, jd);
  }
}

/* ---------------- project level ---------------- */

function writeProjectProps(ctx: ExportCtx, root: XElement): void {
  const cur = contextMap(child(root, "properties"), "property");
  const want = Object.fromEntries(Object.entries(ctx.doc.meta.props).filter(([k]) => !k.startsWith("qet:")));
  if (JSON.stringify(Object.entries(cur).sort()) === JSON.stringify(Object.entries(want).sort())) return;
  const props = ensureChild(ctx.x, root, "properties", ["newdiagrams", "diagram", "collection"]);
  const existing = new Map(children(props, "property").map((p) => [attr(p, "name"), p]));
  for (const [k, p] of existing) if (!(k in want)) removeIndented(p);
  for (const [k, v] of Object.entries(want)) {
    const p = existing.get(k);
    if (p) {
      if (textOf(p) !== v) setText(ctx.x, p, v);
    } else insertIndented(ctx.x, props, createEl(ctx.x, "property", { name: k, show: 1 }, v ? [v] : []));
  }
  collapseIfEmpty(props);
}

function writeTitleBlocks(ctx: ExportCtx, root: XElement): void {
  const tpls = Object.values(ctx.doc.titleBlocks).filter((t) => !(t.name === DEFAULT_TB && !t.xml));
  if (!tpls.length) return;
  let container = child(root, "titleblocktemplates");
  const existing = new Map(children(container, "titleblocktemplate").map((t) => [attr(t, "name"), t]));
  for (const t of tpls) {
    const old = existing.get(t.name);
    if (old) {
      let unchanged = !!t.xml && !titleBlockModified(t);
      if (!unchanged) {
        try {
          unchanged = stableStringify(stripXml(parseTitleBlockNode(old))) === stableStringify(stripXml(t));
        } catch {
          unchanged = false;
        }
      }
      if (unchanged) continue;
    }
    const node = parseElement(serializeTitleBlockTemplate(t));
    const imported = ctx.x.importNode(node, true) as XElement;
    if (old) replaceIndented(ctx.x, old, imported);
    else {
      container ??= ensureChild(ctx.x, root, "titleblocktemplates", ["properties", "newdiagrams", "diagram", "collection"]);
      insertIndented(ctx.x, container, imported);
    }
    ctx.rep.add("supported", "title blocks", "title block templates written");
  }
}
const stripXml = (t: TitleBlockTemplate) => ({ name: t.name, rows: t.rows, cols: t.cols, cells: t.cells });

/* ---------------- diagrams ---------------- */

function newDiagramNode(ctx: ExportCtx, root: XElement): XElement {
  const nd = child(root, "newdiagrams");
  const d = ctx.x.createElement("diagram");
  const border = child(nd, "border");
  const inset = child(nd, "inset");
  if (border) setAttrs(d, allAttrs(border));
  if (inset) setAttrs(d, allAttrs(inset));
  setAttrs(d, { freezeNewElement: "false", freezeNewConductor: "false" });
  const dc = ctx.x.createElement("defaultconductor");
  const condDefaults = child(nd, "conductors");
  setAttrs(dc, condDefaults ? allAttrs(condDefaults) : DEFAULT_CONDUCTOR_ATTRS);
  d.appendChild(dc);
  return d;
}

type ElemOut = {
  node: XElement;
  uuid: string;
  /** pin id -> numeric terminal id */
  ids: Map<string, number>;
  /** pin id -> scene dock (QET coords) */
  dock: (pinId: string) => Pt | null;
  pin: (pinId: string) => PinDef | undefined;
  label: string;
  defName: string;
  /** element orientation (0..3) for scene terminal orientation */
  rot: number;
};

function setNumAttr(el: XElement, name: string, v: number): void {
  const cur = optNum(el, name);
  if (cur === undefined || Math.abs(cur - v) > 1e-9) el.setAttribute(name, fmt(v));
}

function writeTerminals(ctx: ExportCtx, el: XElement, def: ElementDef, prev: Record<string, string> | undefined, alloc: () => number, taken: Set<number>): Map<string, number> {
  // keep a matching list untouched
  const existing = child(el, "terminals");
  if (existing) {
    const m = matchInstanceTerminals(el, { ...def, pins: [...def.pins] }, false);
    const entries = children(existing, "terminal");
    // placeholders: QET resolves the real definition itself, never rewrite their terminal list
    if (def.placeholder || (m.size === def.pins.length && entries.length === def.pins.length)) {
      const ids = new Map<string, number>();
      for (const [n, pinId] of m) ids.set(pinId, n);
      return ids;
    }
  }
  const ids = new Map<string, number>();
  const terms = ctx.x.createElement("terminals");
  for (const p of def.pins) {
    const want = prev?.[p.id] !== undefined ? parseInt(prev[p.id], 10) : NaN;
    const id = Number.isFinite(want) && !taken.has(want) ? want : alloc();
    taken.add(id);
    ids.set(p.id, id);
    const off = dockElmtOffset(p.orient);
    // Terminal::toXml(): x/y = dock_elmt_, orientation = definition orientation (int)
    terms.appendChild(createEl(ctx.x, "terminal", { x: p.x + off.x, y: p.y + off.y, orientation: ORIENT_INDEX[p.orient], id }));
  }
  if (existing) replaceIndented(ctx.x, existing, terms);
  else insertIndented(ctx.x, el, terms, children(el)[0] ?? null);
  return ids;
}

function writeElementInfo(ctx: ExportCtx, el: XElement, info: Record<string, string>, def: ElementDef): void {
  const old = child(el, "elementInformations");
  const nonEmpty = (m: Record<string, string>) => Object.fromEntries(Object.entries(m).filter(([, v]) => v.trim() !== ""));
  // values the importer derived from pre-0.7 text fields count as unchanged
  const cur = nonEmpty({ ...legacyInstanceTexts(el, def).info, ...contextMap(old, "elementInformation") });
  const want = nonEmpty(info);
  if (JSON.stringify(Object.entries(cur).sort()) === JSON.stringify(Object.entries(want).sort())) return;
  const shows = new Map(children(old, "elementInformation").map((p) => [attr(p, "name"), attr(p, "show", "1")]));
  const neu = ctx.x.createElement("elementInformations");
  // DiagramContext::toXml(): empty elementInformation values are skipped
  for (const [k, v] of Object.entries(want).sort(([a], [b]) => a.localeCompare(b))) {
    neu.appendChild(createEl(ctx.x, "elementInformation", { show: shows.get(k) ?? "1", name: k }, [v]));
  }
  if (old) replaceIndented(ctx.x, old, neu);
  else insertIndented(ctx.x, el, neu, child(el, "dynamic_texts") ?? child(el, "texts_groups"));
}

function dynTextNode(ctx: ExportCtx, t: { x: number; y: number; from: string; info: string | null; text: string; size: number; rotation: number; halign: "left" | "center" | "right"; valign?: "top" | "center" | "bottom"; uuid: string; color?: string; frame?: boolean; width?: number }): XElement {
  const n = createEl(ctx.x, "dynamic_elmt_text", {
    x: t.x,
    y: t.y,
    rotation: t.rotation,
    uuid: bracedUuid(t.uuid),
    frame: t.frame ? "true" : "false",
    text_width: t.width ?? -1,
    font: qtFontString("Sans Serif", t.size),
    keep_visual_rotation: "true",
    text_from: t.from,
    Halignment: halignToQet(t.halign),
    Valignment: t.valign === "bottom" ? "AlignBottom" : t.valign === "center" ? "AlignVCenter" : "AlignTop",
  });
  const tn = ctx.x.createElement("text");
  setText(ctx.x, tn, t.text);
  n.appendChild(tn);
  if (t.info) n.appendChild(createEl(ctx.x, "info_name", {}, [t.info]));
  if (t.color) n.appendChild(createEl(ctx.x, "color", {}, [t.color]));
  return n;
}

function writeDynamicTexts(ctx: ExportCtx, el: XElement, inst: ElemInst, def: ElementDef, fresh: boolean): void {
  if (!fresh) {
    // pre-0.7 instance texts that were not edited stay in their legacy form
    const legacy = legacyInstanceTexts(el, def);
    if (legacy.texts.length && sameLegacy(legacy.texts, inst.texts)) return;
  }
  let container = child(el, "dynamic_texts");
  const nodes = children(container, "dynamic_elmt_text");
  const byUuid = new Map(nodes.map((n) => [normUuid(optAttr(n, "uuid")), n]));
  const used = new Set<XElement>();
  const defTexts = def.prims.filter((p): p is Extract<typeof p, { t: "dyntext" }> => p.t === "dyntext");
  const coveredDef = new Set<number>();
  const out: XElement[] = [];

  for (const t of inst.texts) {
    const key = normUuid(t.uuid ?? t.id);
    const node = byUuid.get(key);
    // match a definition text for default positions / fresh instances
    const di = defTexts.findIndex((p, i) => !coveredDef.has(i) && (t.info ? p.from === "ElementInfo" && p.info === t.info : p.from !== "ElementInfo" && p.text === t.text));
    if (di >= 0) coveredDef.add(di);
    const dp = di >= 0 ? defTexts[di] : undefined;
    if (node) {
      used.add(node);
      if (t.x !== null) setNumAttr(node, "x", t.x);
      if (t.y !== null) setNumAttr(node, "y", t.y);
      const tf = attr(node, "text_from", "UserText");
      if (tf === "UserText") {
        const tn = child(node, "text") ?? node.appendChild(ctx.x.createElement("text"));
        if (isElement(tn) && textOf(tn) !== t.text) setText(ctx.x, tn, t.text);
      }
      if (t.override?.rotation !== undefined) setNumAttr(node, "rotation", t.override.rotation);
      if (t.override?.size !== undefined) {
        const f = parseQtFont(optAttr(node, "font"));
        if (f.size !== t.override.size) node.setAttribute("font", qtFontString(f.family ?? "Sans Serif", t.override.size, f.bold, f.italic));
      }
      if (t.override?.align && halignFromQet(optAttr(node, "Halignment")) !== t.override.align) node.setAttribute("Halignment", halignToQet(t.override.align));
      out.push(node);
      continue;
    }
    const fallbackPos = { x: (def.width - def.hotspotX) + 2, y: -def.hotspotY };
    out.push(
      dynTextNode(ctx, {
        x: t.x ?? dp?.x ?? fallbackPos.x,
        y: t.y ?? dp?.y ?? fallbackPos.y,
        from: t.info ? "ElementInfo" : "UserText",
        info: t.info,
        text: t.info ? (inst.info[t.info] ?? t.text) : t.text,
        size: t.override?.size ?? dp?.size ?? 9,
        rotation: t.override?.rotation ?? dp?.rotation ?? 0,
        halign: t.override?.align ?? dp?.halign ?? "left",
        valign: dp?.valign,
        uuid: t.uuid && isUuid(t.uuid) ? t.uuid : isUuid(t.id) ? t.id : uid(),
        color: t.override?.color ?? dp?.color,
        frame: dp?.frame,
        width: dp?.width,
      }),
    );
  }
  // Element::fromXml() discards the definition's texts and only loads the instance ones, so a new
  // instance must carry every definition text explicitly.
  if (fresh) {
    defTexts.forEach((p, i) => {
      if (coveredDef.has(i)) return;
      out.push(
        dynTextNode(ctx, {
          x: p.x,
          y: p.y,
          from: p.from,
          info: p.info ?? null,
          text: p.from === "ElementInfo" && p.info ? (inst.info[p.info] ?? "") : p.text,
          size: p.size,
          rotation: p.rotation,
          halign: p.halign,
          valign: p.valign,
          uuid: uid(),
          color: p.color,
          frame: p.frame,
          width: p.width,
        }),
      );
    });
  }
  const unchanged = out.length === nodes.length && out.every((n, i) => n === nodes[i]);
  if (unchanged) return;
  if (!container) container = ensureChild(ctx.x, el, "dynamic_texts", ["texts_groups"]);
  for (const n of nodes) removeIndented(n);
  for (const n of out) insertIndented(ctx.x, container, n);
  collapseIfEmpty(container);
}

function sceneDockFn(inst: { x: number; y: number; rot: ElemInst["rot"] }, def: ElementDef) {
  const q = { x: inst.x + QET_MARGIN, y: inst.y + QET_MARGIN, rot: inst.rot, mirror: false };
  return (pinId: string): Pt | null => {
    const p = def.pins.find((pp) => pp.id === pinId);
    return p ? toScene(q, p) : null;
  };
}

function writeElement(ctx: ExportCtx, orig: XElement | undefined, inst: ElemInst, alloc: () => number, taken: Set<number>, pageTitle: string): ElemOut | null {
  const def = ctx.doc.defs[inst.defId];
  if (!def) {
    ctx.rep.add("unsupported", "elements", `element without definition (${inst.defId}) dropped`, 1, pageTitle);
    return null;
  }
  ctx.usedDefs.add(inst.defId);
  const fresh = !orig;
  const el = orig ?? ctx.x.createElement("element");
  const type = typePathFor(ctx, inst.defId);
  const typeChanged = !fresh && attr(el, "type") !== type;
  const uuid = isUuid(inst.id) ? normUuid(inst.id) : normUuid(optAttr(el, "uuid")) || uid();
  if (attr(el, "type") !== type) el.setAttribute("type", type);
  // pre-0.7 files have no element uuids and reference terminals by numeric id: don't add one
  if ((fresh || el.hasAttribute("uuid") || ctx.useUuidRefs) && normUuid(optAttr(el, "uuid")) !== uuid) el.setAttribute("uuid", bracedUuid(uuid));
  setNumAttr(el, "x", inst.x + QET_MARGIN);
  setNumAttr(el, "y", inst.y + QET_MARGIN);
  if (int(el, "orientation", -1) !== inst.rot) el.setAttribute("orientation", String(inst.rot));
  if (inst.z !== undefined) setNumAttr(el, "z", inst.z);
  if (fresh) {
    setAttrs(el, { prefix: def.prefix ?? "", freezeLabel: inst.refLocked ? "true" : "false", z: inst.z ?? 10, is_movable: inst.locked ? 0 : 1 });
  } else {
    if (inst.refLocked !== undefined && (attr(el, "freezeLabel") === "true") !== inst.refLocked) el.setAttribute("freezeLabel", inst.refLocked ? "true" : "false");
    if (inst.locked !== undefined && (attr(el, "is_movable", "1") === "0") !== inst.locked) el.setAttribute("is_movable", inst.locked ? "0" : "1");
  }
  if (inst.mirror) ctx.rep.add("degraded", "elements", "mirrored elements exported unmirrored (QET cannot mirror instances)", 1, pageTitle);
  if (def.placeholder) ctx.rep.add("degraded", "elements", "instances of unavailable definitions keep their original reference", 1, pageTitle);

  const ids = writeTerminals(ctx, el, def, typeChanged ? undefined : inst.qet?.terminalIds, alloc, taken);
  if (fresh) {
    el.appendChild(ctx.x.createElement("inputs"));
  }
  writeElementInfo(ctx, el, inst.info, def);
  writeDynamicTexts(ctx, el, inst, def, fresh || typeChanged);
  if (fresh) el.appendChild(ctx.x.createElement("texts_groups"));
  return {
    node: el,
    uuid,
    ids,
    dock: sceneDockFn(inst, def),
    pin: (id) => def.pins.find((p) => p.id === id),
    label: inst.info.label ?? inst.info.formula ?? "",
    defName: def.name,
    rot: inst.rot,
  };
}

function writeJunction(ctx: ExportCtx, orig: XElement | undefined, j: { id: string; x: number; y: number; qetElemId?: string }, alloc: () => number, taken: Set<number>): ElemOut {
  ctx.needJunctionDef = true;
  const def = junctionDef();
  const el = orig ?? ctx.x.createElement("element");
  const uuid = normUuid(j.qetElemId) && isUuid(j.qetElemId ?? "") ? normUuid(j.qetElemId) : isUuid(j.id) ? normUuid(j.id) : uid();
  if (attr(el, "type") !== JUNCTION_DEF_PATH) el.setAttribute("type", JUNCTION_DEF_PATH);
  if (normUuid(optAttr(el, "uuid")) !== uuid) el.setAttribute("uuid", bracedUuid(uuid));
  setNumAttr(el, "x", j.x + QET_MARGIN);
  setNumAttr(el, "y", j.y + QET_MARGIN);
  if (!orig) setAttrs(el, { orientation: 0, prefix: "", freezeLabel: "false", z: 10, is_movable: 1 });
  const ids = writeTerminals(ctx, el, def, undefined, alloc, taken);
  if (!orig) {
    el.appendChild(ctx.x.createElement("inputs"));
    el.appendChild(ctx.x.createElement("dynamic_texts"));
    el.appendChild(ctx.x.createElement("texts_groups"));
  }
  const at = { x: j.x + QET_MARGIN, y: j.y + QET_MARGIN };
  return { node: el, uuid, ids, dock: () => at, pin: () => def.pins[0], label: "", defName: def.name, rot: 0 };
}

const REF_ATTRS = (n: 1 | 2) => [`element${n}`, `element${n}_label`, `element${n}_linked`, `element${n}_name`, `terminal${n}`, `terminalname${n}`];

function writeConductorRefs(ctx: ExportCtx, c: XElement, n: 1 | 2, out: ElemOut, pinId: string): void {
  const pin = out.pin(pinId);
  const pinUuid = pin && isUuid(pin.id) ? normUuid(pin.id) : "";
  if (ctx.useUuidRefs && pinUuid) {
    // Conductor::toXml(): uuid scheme when the terminal has a uuid
    const changed = normUuid(optAttr(c, `element${n}`)) !== out.uuid || normUuid(optAttr(c, `terminal${n}`)) !== pinUuid;
    if (changed) {
      setAttrs(c, {
        [`element${n}`]: bracedUuid(out.uuid),
        [`element${n}_label`]: out.label,
        [`element${n}_name`]: out.defName,
        [`terminal${n}`]: bracedUuid(pinUuid),
        [`terminalname${n}`]: pin?.name ?? "",
      });
      if (changed) c.removeAttribute(`element${n}_linked`);
    }
  } else {
    const id = out.ids.get(pinId);
    for (const a of REF_ATTRS(n)) if (a !== `terminal${n}`) c.removeAttribute(a);
    c.setAttribute(`terminal${n}`, String(id ?? 0));
  }
}

function writeSegments(ctx: ExportCtx, c: XElement, pts: Pt[]): void {
  for (const s of children(c, "segment")) removeIndented(s);
  const segs = pointsToSegments(pts);
  let ref = c.firstChild;
  // skip leading whitespace so segments stay first (Conductor::toXml order)
  while (ref && !isElement(ref)) ref = ref.nextSibling;
  for (const s of segs) {
    const node = createEl(ctx.x, "segment", { orientation: s.horizontal ? "horizontal" : "vertical", length: s.length });
    if (ref) insertIndented(ctx.x, c, node, ref);
    else insertIndented(ctx.x, c, node);
  }
}

/** Rebuild the element list of a container, touching the DOM only when something changed. */
function rebuildList(ctx: ExportCtx, container: XElement, tag: string, next: XElement[]): void {
  const cur = children(container, tag);
  if (cur.length === next.length && cur.every((n, i) => n === next[i])) return;
  for (const n of cur) removeIndented(n);
  for (const n of next) insertIndented(ctx.x, container, n);
  collapseIfEmpty(container);
}

function writeDiagram(ctx: ExportCtx, diag: XElement, page: Page, order: number): void {
  const title = page.title;
  const b = page.border;
  /* attributes (BorderTitleBlock::borderToXml, TitleBlockProperties::toXml) */
  if (attr(diag, "title") !== page.title) diag.setAttribute("title", page.title);
  if (int(diag, "order", -1) !== order) diag.setAttribute("order", String(order));
  if (int(diag, "cols", -1) !== b.cols) diag.setAttribute("cols", String(b.cols));
  if (int(diag, "rows", -1) !== b.rows) diag.setAttribute("rows", String(b.rows));
  setNumAttr(diag, "colsize", b.colW);
  setNumAttr(diag, "rowsize", b.rowH);
  if ((attr(diag, "displaycols") !== "false") !== b.showCols || !diag.hasAttribute("displaycols")) diag.setAttribute("displaycols", b.showCols ? "true" : "false");
  if ((attr(diag, "displayrows") !== "false") !== b.showRows || !diag.hasAttribute("displayrows")) diag.setAttribute("displayrows", b.showRows ? "true" : "false");
  setNumAttr(diag, "height", b.rows * b.rowH + HEADER);
  if (isUuid(page.id) && normUuid(optAttr(diag, "uuid")) !== normUuid(page.id) && diag.hasAttribute("uuid")) diag.setAttribute("uuid", bracedUuid(page.id));

  const f = page.titleBlock.fields;
  for (const k of TB_FIELDS) {
    if (k === "title") continue;
    const v = f[k];
    if (v !== undefined && attr(diag, k) !== v) diag.setAttribute(k, v);
  }
  const custom = Object.fromEntries(Object.entries(f).filter(([k]) => !isBuiltinField(k)).map(([k, v]) => [customName(k), v]));
  const oldProps = child(diag, "properties");
  const curCustom = contextMap(oldProps, "property");
  if (JSON.stringify(Object.entries(curCustom).sort()) !== JSON.stringify(Object.entries(custom).sort())) {
    const shows = new Map(children(oldProps, "property").map((p) => [attr(p, "name"), attr(p, "show", "1")]));
    const neu = ctx.x.createElement("properties");
    for (const [k, v] of Object.entries(custom)) neu.appendChild(createEl(ctx.x, "property", { show: shows.get(k) ?? "1", name: k }, v ? [v] : []));
    if (oldProps) {
      if (Object.keys(custom).length) replaceIndented(ctx.x, oldProps, neu);
      else removeIndented(oldProps);
    } else if (Object.keys(custom).length) insertIndented(ctx.x, diag, neu, children(diag)[0] ?? null);
  }
  const tpl = page.titleBlock.template;
  if (tpl === DEFAULT_TB) {
    const keep = page.meta["qet:titleblocktemplate"];
    if (keep) {
      const i = keep.indexOf(":");
      setAttrs(diag, { titleblocktemplateCollection: keep.slice(0, i), titleblocktemplate: keep.slice(i + 1) });
    } else if (diag.hasAttribute("titleblocktemplate") && attr(diag, "titleblocktemplate") !== "default") {
      diag.removeAttribute("titleblocktemplate");
      diag.removeAttribute("titleblocktemplateCollection");
    }
  } else if (attr(diag, "titleblocktemplate") !== tpl || attr(diag, "titleblocktemplateCollection") !== "embedded") {
    if (!ctx.doc.titleBlocks[tpl]) ctx.rep.add("degraded", "title blocks", `page uses unknown title block template "${tpl}"`, 1, title);
    setAttrs(diag, { titleblocktemplate: tpl, titleblocktemplateCollection: "embedded" });
  }

  /* elements */
  const elemsFound = child(diag, "elements");
  const origEls = children(elemsFound, "element");
  const origByIdx = (i: number | undefined) => (i !== undefined ? origEls[i] : undefined);
  const keepEls = (page.meta["qet:keepElements"] ?? "").split(",").filter(Boolean).map(Number);
  const junctionOrig = new Map<string, XElement>();
  for (const e of origEls) if (attr(e, "type") === JUNCTION_DEF_PATH) junctionOrig.set(normUuid(optAttr(e, "uuid")), e);

  // numeric terminal ids must be unique per diagram (Element::fromXml rejects conflicts)
  const taken = new Set<number>();
  const claimed = new Set<XElement>();
  for (const inst of page.elements) {
    const o = origByIdx(inst.qet?.idx);
    if (o && !claimed.has(o)) claimed.add(o);
  }
  for (const j of page.junctions) {
    const o = junctionOrig.get(normUuid(j.qetElemId ?? j.id));
    if (o) claimed.add(o);
  }
  for (const i of keepEls) if (origEls[i]) claimed.add(origEls[i]);
  for (const o of claimed) for (const t of subChildren(o, "terminals", "terminal")) taken.add(int(t, "id", -1));
  let next = Math.max(-1, ...taken) + 1;
  const alloc = () => {
    while (taken.has(next)) next++;
    return next++;
  };

  const outNodes: XElement[] = [];
  const outById = new Map<string, ElemOut>();
  const usedOrig = new Set<XElement>();
  for (const inst of page.elements) {
    let o = origByIdx(inst.qet?.idx);
    if (o && (usedOrig.has(o) || attr(o, "type") === JUNCTION_DEF_PATH)) o = undefined;
    if (o) usedOrig.add(o);
    const res = writeElement(ctx, o, inst, alloc, taken, title);
    if (!res) continue;
    outNodes.push(res.node);
    outById.set(inst.id, res);
  }
  const junctionOut = new Map<string, ElemOut>();
  for (const j of page.junctions) {
    let o = junctionOrig.get(normUuid(j.qetElemId ?? j.id));
    if (o && usedOrig.has(o)) o = undefined;
    if (o) usedOrig.add(o);
    const res = writeJunction(ctx, o, j, alloc, taken);
    outNodes.push(res.node);
    junctionOut.set(j.id, res);
  }

  /* conductors */
  const condFound = child(diag, "conductors");
  const origConds = children(condFound, "conductor");
  const keepConds = (page.meta["qet:keepConductors"] ?? "").split(",").filter(Boolean).map(Number);
  const baseAttrs = child(diag, "defaultconductor") ? allAttrs(child(diag, "defaultconductor") as XElement) : DEFAULT_CONDUCTOR_ATTRS;
  const condOut: XElement[] = [];
  const usedConds = new Set<XElement>();
  let freeEnds = 0;

  const endOut = (end: WireEnd, at: Pt): { out: ElemOut; pin: string } => {
    if (end.k === "pin") {
      const o = outById.get(end.el);
      if (o && o.pin(end.pin)) return { out: o, pin: end.pin };
      ctx.rep.add("degraded", "conductors", "wire end referencing a missing element/pin attached to a junction", 1, title);
    } else if (end.k === "junction") {
      const o = junctionOut.get(end.j);
      if (o) return { out: o, pin: JUNCTION_PIN_UUID };
      ctx.rep.add("degraded", "conductors", "wire end referencing a missing junction attached to a new junction", 1, title);
    } else freeEnds++;
    // free end: materialise a junction instance at the end point so QET can load the conductor
    const res = writeJunction(ctx, undefined, { id: uid(), x: at.x, y: at.y }, alloc, taken);
    outNodes.push(res.node);
    return { out: res, pin: JUNCTION_PIN_UUID };
  };

  for (const w of page.wires) {
    if (w.pts.length < 1 && (w.a.k === "free" || w.b.k === "free")) {
      ctx.rep.add("unsupported", "conductors", "wire without geometry dropped", 1, title);
      continue;
    }
    const first = w.pts[0] ?? { x: 0, y: 0 };
    const last = w.pts[w.pts.length - 1] ?? first;
    const A = endOut(w.a, first);
    const B = endOut(w.b, last);
    const d1 = A.out.dock(A.pin);
    const d2 = B.out.dock(B.pin);
    if (!d1 || !d2) continue;
    if (A.out === B.out && A.pin === B.pin) {
      ctx.rep.add("unsupported", "conductors", "wire connecting a terminal to itself dropped", 1, title);
      continue;
    }
    let c = w.qet?.idx !== undefined ? origConds[w.qet.idx] : undefined;
    if (c && usedConds.has(c)) c = undefined;
    const fresh = !c;
    if (c) usedConds.add(c);
    else {
      c = ctx.x.createElement("conductor");
      setAttrs(c, baseAttrs);
      setAttrs(c, { x: 0, y: 0, freezeLabel: "false" });
    }
    // user-level attributes captured on import (color, type, function, ...)
    if (w.qet?.attrs) {
      for (const [k, v] of Object.entries(w.qet.attrs)) {
        if (/^(element|terminal|terminalname)[12]/.test(k) || k === "x" || k === "y" || k === "uuid") continue;
        if (attr(c, k) !== v || !c.hasAttribute(k)) c.setAttribute(k, v);
      }
    }
    if (w.override?.color && attr(c, "color") !== w.override.color) c.setAttribute("color", w.override.color);
    if (attr(c, "num") !== (w.label ?? "")) c.setAttribute("num", w.label ?? "");
    if (w.cable !== undefined && attr(c, "cable") !== w.cable) c.setAttribute("cable", w.cable);
    if (fresh && isUuid(w.id)) c.setAttribute("uuid", bracedUuid(w.id));
    writeConductorRefs(ctx, c, 1, A.out, A.pin);
    writeConductorRefs(ctx, c, 2, B.out, B.pin);

    // geometry: keep the stored segments when they still describe the same path
    const body = w.pts.map((p) => shift(p, QET_MARGIN));
    // pathFromXml() tolerates 1 unit between the chained segments and terminal2
    const endsNear = body.length > 1 && Math.hypot(body[body.length - 1].x - d2.x, body[body.length - 1].y - d2.y) <= 1;
    const want = normalizePath([d1, ...body, ...(endsNear ? [] : [d2])]);
    const pinA = A.out.pin(A.pin);
    const pinB = B.out.pin(B.pin);
    const o1 = pinA ? rotOrient(pinA.orient, A.out.rot, false) : "n";
    const o2 = pinB ? rotOrient(pinB.orient, B.out.rot, false) : "n";
    const segs = fresh ? [] : readSegments(c);
    const current = conductorPoints(segs, d1, o1, d2, o2);
    if (fresh || !polyEq(normalizePath(current.pts), want)) {
      const auto = normalizePath(qetAutoPath(d1, o1, d2, o2));
      if (polyEq(auto, want)) {
        for (const s of children(c, "segment")) removeIndented(s);
      } else writeSegments(ctx, c, want);
    }
    if (fresh && !child(c, "sequentialNumbers")) c.appendChild(ctx.x.createElement("sequentialNumbers"));
    condOut.push(c);
  }
  if (freeEnds) ctx.rep.add("degraded", "conductors", "free wire ends attached to generated junction elements", freeEnds, title);
  for (const i of keepConds) if (origConds[i] && !usedConds.has(origConds[i])) condOut.push(origConds[i]);
  for (const i of keepEls) if (origEls[i] && !usedOrig.has(origEls[i])) outNodes.push(origEls[i]);

  // containers are created only when needed (Diagram::toXml omits empty ones)
  if (elemsFound || outNodes.length) rebuildList(ctx, elemsFound ?? ensureChild(ctx.x, diag, "elements", ["conductors", "inputs", "images", "shapes", "tables"]), "element", outNodes);
  if (condFound || condOut.length) rebuildList(ctx, condFound ?? ensureChild(ctx.x, diag, "conductors", ["inputs", "images", "shapes", "tables"]), "conductor", condOut);

  /* independent texts */
  const inputsFound = child(diag, "inputs");
  const origInputs = children(inputsFound, "input");
  const textOut: XElement[] = [];
  const usedInputs = new Set<XElement>();
  for (const t of page.texts) {
    let n = t.qet?.idx !== undefined ? origInputs[t.qet.idx] : undefined;
    if (n && usedInputs.has(n)) n = undefined;
    if (n) {
      usedInputs.add(n);
      setNumAttr(n, "x", t.x + QET_MARGIN);
      setNumAttr(n, "y", t.y + QET_MARGIN);
      if (htmlToPlain(attr(n, "text")) !== t.text) n.setAttribute("text", plainToHtmlIfNeeded(t.text));
      if (t.override?.rotation !== undefined) setNumAttr(n, "rotation", t.override.rotation);
      if (t.override?.size !== undefined) {
        const f = parseQtFont(optAttr(n, "font"));
        if (f.size !== t.override.size) n.setAttribute("font", qtFontString(f.family ?? "Sans Serif", t.override.size, f.bold, f.italic));
      }
    } else {
      n = createEl(ctx.x, "input", {
        x: t.x + QET_MARGIN,
        y: t.y + QET_MARGIN,
        text: plainToHtmlIfNeeded(t.text),
        rotation: t.override?.rotation ?? 0,
        font: qtFontString("Sans Serif", t.override?.size ?? 9),
      });
    }
    textOut.push(n);
  }
  if (inputsFound || textOut.length) rebuildList(ctx, inputsFound ?? ensureChild(ctx.x, diag, "inputs", ["images", "shapes", "tables"]), "input", textOut);
}

/**
 * Export a Doc to a .qet project. When the Doc came from `importQet` the original XML is patched
 * in place (unknown nodes, shapes, properties, definitions and templates stay byte-identical);
 * otherwise a complete project is generated.
 */
export function exportQet(doc: Doc): { xml: string; report: CompatReport } {
  const src = doc.qet?.source;
  const x = parseXml(src ?? skeletonProject(doc));
  const root = x.documentElement as XElement;
  if (root.tagName !== "project") throw new Error("source is not a QElectroTech project");
  const version = attr(root, "version") || QET_VERSION;
  const ctx: ExportCtx = {
    doc,
    x,
    rep: new Reporter(),
    useUuidRefs: qetVersionNumber(version) >= UUID_REFS_SINCE,
    typeOf: new Map(),
    usedDefs: new Set(),
    needJunctionDef: false,
  };
  if (attr(root, "title") !== doc.meta.title) root.setAttribute("title", doc.meta.title);
  writeProjectProps(ctx, root);
  writeTitleBlocks(ctx, root);

  const origDiagrams = diagramNodes(root);
  const pages = [...doc.pages].sort((a, b) => a.order - b.order);
  const used = new Set<XElement>();
  const outDiagrams: XElement[] = [];
  pages.forEach((p, i) => {
    let d = p.qet?.idx !== undefined ? origDiagrams[p.qet.idx] : undefined;
    if (d && used.has(d)) d = d.cloneNode(true) as XElement;
    if (!d) {
      d = newDiagramNode(ctx, root);
      if (isUuid(p.id)) d.setAttribute("uuid", bracedUuid(p.id));
    }
    used.add(d);
    writeDiagram(ctx, d, p, i + 1);
    outDiagrams.push(d);
  });
  const dropped = origDiagrams.filter((d) => !used.has(d)).length;
  if (dropped) ctx.rep.add("supported", "pages", "deleted folios removed", dropped);

  const same = outDiagrams.length === origDiagrams.length && outDiagrams.every((d, i) => d === origDiagrams[i]);
  if (!same) {
    for (const d of origDiagrams) removeIndented(d);
    let ref: XElement | null = null;
    for (const t of ["terminal_strips", "collection"]) if ((ref = child(root, t))) break;
    for (const d of outDiagrams) insertIndented(x, root, d, ref);
  }
  writeCollection(ctx, root);

  const out = serializeXml(x) + (src === undefined || src.endsWith("\n") ? "\n" : "");
  let elementCount = 0;
  let wireCount = 0;
  for (const p of pages) {
    elementCount += p.elements.length;
    wireCount += p.wires.length;
  }
  ctx.rep.add("supported", "export", "folios written", pages.length);
  if (elementCount) ctx.rep.add("supported", "export", "elements written", elementCount);
  if (wireCount) ctx.rep.add("supported", "export", "conductors written", wireCount);
  return { xml: out, report: makeReport(doc, doc.qet?.filename ?? `${doc.meta.title || "project"}.qet`, version, ctx.rep) };
}

/* ------------------------------------------------------------------ */
/* Structural validation (mirrors the checks of QET's loaders)          */
/* ------------------------------------------------------------------ */

/**
 * Check a .qet document against the minimal requirements of QET's loaders
 * (Element::valideXml, Terminal::valideXml, Conductor::valideXml + findTerminal,
 * Element::buildFromXml). Returns human readable problems (empty = OK).
 */
export function validateQet(xml: string): string[] {
  const problems: string[] = [];
  const x = parseXml(xml);
  const root = x.documentElement as XElement;
  if (root.tagName !== "project") return ["root is not <project>"];
  const coll = child(root, "collection");
  const embedded = new Map<string, XElement>();
  const walk = (cat: XElement, path: string[]) => {
    for (const c of children(cat)) {
      if (c.tagName === "category") walk(c, [...path, attr(c, "name")]);
      else if (c.tagName === "element") {
        const d = child(c, "definition");
        if (d) embedded.set(`embed://${[...path, attr(c, "name")].join("/")}`, d);
      }
    }
  };
  if (coll) walk(coll, []);
  const isInt = (e: XElement, a: string) => /^-?\d+$/.test(attr(e, a).trim());
  for (const [p, d] of embedded) {
    if (attr(d, "type") !== "element") problems.push(`${p}: definition type != element`);
    for (const a of ["width", "height", "hotspot_x", "hotspot_y"]) if (!isInt(d, a)) problems.push(`${p}: ${a} must be an integer`);
    if (!children(child(d, "description")).length) problems.push(`${p}: empty description`);
  }
  diagramNodes(root).forEach((diag, di) => {
    const ids = new Map<number, { uuid: string; t: XElement }>();
    const elUuids = new Map<string, XElement>();
    for (const e of subChildren(diag, "elements", "element")) {
      const type = attr(e, "type");
      if (!type || !Number.isFinite(Number(attr(e, "x"))) || !Number.isFinite(Number(attr(e, "y")))) problems.push(`diagram ${di}: element missing type/x/y`);
      if (type.startsWith("embed://") && !embedded.has(type)) problems.push(`diagram ${di}: ${type} not embedded`);
      const u = normUuid(optAttr(e, "uuid"));
      if (u) elUuids.set(u, e);
      for (const t of subChildren(e, "terminals", "terminal")) {
        const id = Number(attr(t, "id"));
        if (!["x", "y", "orientation", "id"].every((a) => t.hasAttribute(a)) || !Number.isInteger(id)) problems.push(`diagram ${di}: invalid instance terminal`);
        else if (ids.has(id)) problems.push(`diagram ${di}: duplicate terminal id ${id}`);
        else ids.set(id, { uuid: u, t });
      }
    }
    for (const c of subChildren(diag, "conductors", "conductor")) {
      for (const n of [1, 2] as const) {
        if (!c.hasAttribute(`terminal${n}`)) {
          problems.push(`diagram ${di}: conductor without terminal${n}`);
          continue;
        }
        if (c.hasAttribute(`element${n}`)) {
          const e = elUuids.get(normUuid(attr(c, `element${n}`)));
          if (!isUuid(attr(c, `element${n}`)) || !isUuid(attr(c, `terminal${n}`))) problems.push(`diagram ${di}: conductor with invalid uuid ref`);
          else if (!e) problems.push(`diagram ${di}: conductor element${n} not found`);
          else {
            const d = embedded.get(attr(e, "type"));
            const tu = normUuid(attr(c, `terminal${n}`));
            if (d && !subChildren(d, "description", "terminal").some((t) => normUuid(optAttr(t, "uuid")) === tu)) problems.push(`diagram ${di}: conductor terminal${n} uuid not in definition`);
          }
        } else if (!ids.has(Number(attr(c, `terminal${n}`)))) problems.push(`diagram ${di}: conductor terminal${n} id not found`);
      }
    }
  });
  return problems;
}
